- hosts: docker_servers


  tasks:
    - name: install redis server
      # apt-get update && apt-get install redis-server
      ansible.builtin.apt: # имя модуля Ansible
        name: redis-server
        state: present
        update_cache: yes
      become: yes

    - name: install git 
      ansible.builtin.apt: 
        name: git
        state: present
        update_cache: yes
      become: yes


